# /etc/zsh/zlogin: system-wide .zlogin file for zsh(1).
#
# This file is sourced only for login shells. It
# should contain commands that should be executed only
# in login shells. It should be used to set the terminal
# type and run a series of external commands (fortune,
# msgs, from, etc.)
#
# Global Order: zshenv, zprofile, zshrc, zlogin

() {
    setopt localoptions EXTENDED_GLOB CSH_NULL_GLOB

    if [[ -d /etc/zsh/zlogin.d ]]; then
	for zlogin_snipplet in /etc/zsh/zlogin.d/[0-9][0-9]-*[^~] ; do
	    if [[ "${zlogin_snipplet:e}" != zwc ]]; then
		source $zlogin_snipplet
	    fi
	done
    fi
}
