# /etc/zsh/zprofile: system-wide .zprofile file for zsh(1).
#
# This file is sourced only for login shells (i.e. shells
# invoked with "-" as the first character of argv[0], and
# shells invoked with the -l flag.)
#
# Global Order: zshenv, zprofile, zshrc, zlogin

() {
    setopt localoptions EXTENDED_GLOB CSH_NULL_GLOB

    if [[ -d /etc/zsh/zprofile.d ]]; then
	for zprofile_snipplet in /etc/zsh/zprofile.d/[0-9][0-9]-*[^~] ; do
	    if [[ "${zprofile_snipplet:e}" != zwc ]]; then
		source $zprofile_snipplet
	    fi
	done
    fi
}
